[package]
name = "res-dedup-hardlink"
version = "0.1.0"
edition = "2024"

[dependencies]
palc = "0.0.1"
rapidhash = "3.1.0"

[profile.release]
lto = true
strip = true
codegen-units = 1
panic = "abort"
